[package]
name = "khanpython/analytics-service-wrapper"
description = "A Promise-based Analytics Service Wrapper for Roblox."
version = "2.0.1"
license = "MIT"
authors = ["khanpython (https://github.com/KhanPython)"]
registry = "https://github.com/upliftgames/wally-index"
realm = "shared"
exclude = [".vscode"]

[dependencies]
promise = "evaera/promise@4.0.0"