[package]
name = "khanpython/analytics-service"
description = "A Promise-based Analytics Service Wrapper for Roblox."
version = "0.0.8"
license = "MIT"
authors = ["khanpython (https://github.com/KhanPython)"]
registry = "https://github.com/upliftgames/wally-index"
realm = "shared"
include = ["src", "src/**", "wally.toml", "wally.lock", "default.project.json", "LICENSE", "README.md"]


[dependencies]
promise = "evaera/promise@4.0.0"